services:
  db:
    image: mariadb:11
    container_name: wp-db-1
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  wordpress:
    build: .
    container_name: wp-backend-1
    restart: always
    depends_on:
      - db
    ports:
      - "6060:80"
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_HOME: ${WP_HOME}
    volumes:
      - wp_uploads:/var/www/html/wp-content/uploads

volumes:
  db_data:
  wp_uploads:
